import { Route, Building2, Sofa, HardHat } from "lucide-react";

// Icon per project type — used for the abstract card treatment (no
// per-project photography exists, so nothing visually implies a
// documentary photo of a specific site).
const typeMeta = {
  "Road Construction": { icon: Route },
  Infrastructure: { icon: HardHat },
  "Building Construction": { icon: Building2 },
  Interior: { icon: Sofa },
};

// RKGC's 11 ongoing Infrastructure works, exactly as listed in the
// company's own "Ongoing Work Infrastructure" source document — project
// name, employer, nature of work, contract value and completed ratio
// are all taken verbatim, in source order. Nothing here is invented;
// where the source gives "Start Soon" it is kept as a status, never
// converted to a 0% progress figure. Source-stated total contract
// value: ₹1,27,07,89,312.49 (see PortfolioSummary in
// InfrastructureExperience.jsx).
const rawProjects = [
  {
    id: 1,
    projectNumber: "01",
    name: "Tundla",
    location: "Tundla",
    employer: "Indian Railway",
    workType: "Boundary Wall",
    category: "Infrastructure",
    service: "RKGC Infrastructure",
    type: "Infrastructure",
    amount: "5,55,53,828.39",
    progress: "70%",
    image: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=1400&q=80",
  },
  {
    id: 2,
    projectNumber: "02",
    name: "Sasni",
    location: "Sasni",
    employer: "North Central Railway",
    workType: "Railway Station Work",
    category: "Infrastructure",
    service: "RKGC Infrastructure",
    type: "Infrastructure",
    amount: "2,27,77,044.66",
    progress: "20%",
    image: "https://images.unsplash.com/photo-1516216628859-9bccecab13ca?w=1400&q=80",
  },
  {
    id: 3,
    projectNumber: "03",
    name: "Pocket Q – Sector 20",
    location: "Sector 20",
    employer: "YEIDA",
    workType: "Development Work",
    category: "Infrastructure",
    service: "RKGC Infrastructure",
    type: "Infrastructure",
    amount: "13,08,65,810.00",
    progress: "80%",
    image: "https://images.unsplash.com/photo-1621905252472-943afaa20e20?w=1400&q=80",
  },
  {
    id: 4,
    projectNumber: "04",
    name: "Pocket E – Sector 20",
    location: "Sector 20",
    employer: "YEIDA",
    workType: "Development Work",
    category: "Infrastructure",
    service: "RKGC Infrastructure",
    type: "Infrastructure",
    amount: "10,21,35,794.44",
    progress: "40%",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1400&q=80",
  },
  {
    id: 5,
    projectNumber: "05",
    name: "Sector 20",
    location: "Sector 20",
    employer: "YEIDA",
    workType: "Drain Work",
    category: "Infrastructure",
    service: "RKGC Infrastructure",
    type: "Infrastructure",
    amount: "4,71,98,298.00",
    progress: "80%",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1400&q=80",
  },
  {
    id: 6,
    projectNumber: "06",
    name: "Sector 56",
    location: "Sector 56",
    employer: "NOIDA",
    workType: "Road Work",
    category: "Infrastructure",
    service: "RKGC Infrastructure",
    type: "Road Construction",
    amount: "5,61,44,882.00",
    progress: "80%",
    image: "https://images.unsplash.com/photo-1494783367193-149034c05e8f?w=1400&q=80",
  },
  {
    id: 7,
    projectNumber: "07",
    name: "Sikandrabad",
    location: "Sikandrabad",
    employer: "UPSIDA",
    workType: "Development Work",
    category: "Infrastructure",
    service: "RKGC Infrastructure",
    type: "Infrastructure",
    amount: "3,71,71,106.00",
    progress: "20%",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1400&q=80",
  },
  {
    id: 8,
    projectNumber: "08",
    name: "Makoda",
    location: "Makoda",
    employer: "GNIDA",
    workType: "Bus Way Work",
    category: "Infrastructure",
    service: "RKGC Infrastructure",
    type: "Infrastructure",
    amount: "5,97,17,372.00",
    progress: "50%",
    image: "https://images.unsplash.com/photo-1494783367193-149034c05e8f?w=1400&q=80",
  },
  {
    id: 9,
    projectNumber: "09",
    name: "Hardoi",
    location: "Hardoi",
    employer: "UPPWD",
    workType: "Development Work",
    category: "Infrastructure",
    service: "RKGC Infrastructure",
    type: "Infrastructure",
    amount: "57,82,00,000.00",
    progress: "20%",
    image: "https://images.unsplash.com/photo-1621905252472-943afaa20e20?w=1400&q=80",
  },
  {
    id: 10,
    projectNumber: "10",
    name: "Ecotech 10",
    location: "Ecotech 10",
    employer: "GNIDA",
    workType: "Development Work",
    category: "Infrastructure",
    service: "RKGC Infrastructure",
    type: "Infrastructure",
    amount: "4,41,98,493.00",
    status: "start-soon",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1400&q=80",
  },
  {
    id: 11,
    projectNumber: "11",
    name: "Sector MU-2",
    location: "Sector MU-2",
    employer: "GNIDA",
    workType: "RCC Work",
    category: "Infrastructure",
    service: "RKGC Infrastructure",
    type: "Building Construction",
    amount: "13,68,26,684.00",
    status: "start-soon",
    image: "https://images.unsplash.com/photo-1541976590-713941681591?w=1400&q=80",
  },
  // RKGC Spaces — unrelated to the Infrastructure source document above.
  {
    id: 12,
    name: "NV Group Office Interior",
    location: "Delhi",
    type: "Interior",
    category: "Spaces",
    service: "RKGC Spaces",
  },
  {
    id: 13,
    name: "Vidya Polymers Interior",
    location: "Noida",
    type: "Interior",
    category: "Spaces",
    service: "RKGC Spaces",
  },
];

export const projects = rawProjects.map((project) => ({
  ...project,
  ...typeMeta[project.type],
}));

// Source-stated total for the 11 ongoing Infrastructure works — never
// recomputed client-side, so it can't silently drift from the document.
export const infrastructurePortfolioTotal = {
  count: 11,
  amount: "1,27,07,89,312.49",
  approxCrore: "127.08",
};
